#!/usr/bin/python2
import argparse

import yandex_tank_api.manager

def parse_options():
    '''parse command line options'''
    parser = argparse.ArgumentParser()
    parser.add_argument("--debug",
                        action='store_true',
                        help='Debug mode of torando',
                        dest='debug',
                        default=False
                        )
    parser.add_argument("--work-dir",
                        help='Working directory (for tests, etc).',
                        default='/var/lib/yandex-tank-api',
                        dest='work_dir'
                        )
    parser.add_argument("--ignore-machine-defaults",
                        help='Ignore tank defaults from /etc/yandex-tank/',
                        default=False,
                        dest='ignore_machine_defaults'
                        )
    return parser.parse_args()

if __name__=='__main__':
    options=parse_options()
    yandex_tank_api.manager.run_server(options)
